name: Code checks

on: push

jobs:
  code_checks:
    strategy:
      matrix:
        pyver: ['3.7', '3.8', '3.9', '3.10', '3.11']
        os: [ ubuntu, macos, windows ]
      fail-fast: true
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 5
    steps:
      - name: Set up Python ${{ matrix.pyver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init
        run: make init
      - name: Lint
        run: make lint
      - name: Tests
        run: make test
