name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2
      - name: build and publish
        run: |
          poetry build
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish -r testpypi
