name: Publish

on:
  release:
    types:
      - created

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        repository_name: 'testpypi'
        repository_url: 'https://test.pypi.org/legacy/'
        pypi_token: ${{ secrets.PYPI_TOKEN }}
